# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan's little corner of the web
email: rnalexander@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Culture, Code, Cooking, and Cocktails
baseurl: "/rna-site" # the subpath of your site, e.g. /blog
url: "https://rnalexander.github.io" # the base hostname & protocol for your site
twitter_username: rnalexander
github_username: rnalexander

# Build settings
markdown: kramdown
